logging:
  level:
    org.springframework.web: debug #debug düzeyindeki log mesajları
    org.springframework.jdbc.datasource: debug
    org.springframework.security: debug

  file: petclinic.log #petclinic.log dosyası otomatik oluşur proje içerisinde